title = "TrueSignal"  # From Git
gitRepoUrl = "https://github.com/x6nny/TrueSignal" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[footer]
style = "dark"
copyright = "Copyright Â© 2026 x6nny. Built with Moonwave and Docusaurus"